n = (input('Digite um valor: '))
print(type(n))
print(n.isalpha())
print(n.isnumeric())
print(n.isalnum())
print(n.isascii())
print(n.isdecimal())
print(n.isdigit())
print(n.isidentifier())
print(n.islower())
print(n.isprintable())
print(n.isspace())
print(n.istitle())
print(n.isupper())
print(n.__init_subclass__())