n = input('Digite um número(de 0 a 9999): ')
print('O seu número escolhido: {}'.format(n))
print('Unidade: {}'.format(n[3]))
print('Dezena: {}'.format(n[2]))
print('Centena: {}'.format(n[1]))
print('Milhar: {}'.format(n[0]))